# Generated by Django 5.2.15 on 2026-09-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_alter_bookmark_id_alter_comment_id_alter_resource_id'),
        ('resource', '0004_alter_bookmark_id_alter_comment_id_alter_resource_id_and_more'),
    ]

    operations = [
    ]
