# Generated by Django 5.2.17 on 2026-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('IT', 'IT / Development'), ('Design', 'UI/UX Design'), ('Marketing', 'Marketing'), ('HR', 'Human Resources'), ('Sales', 'Sales')], default='IT', max_length=50),
        ),
    ]
