# Generated by Django 5.2.17 on 2026-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_milestone_id_alter_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="task_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reference_url",
            field=models.URLField(blank=True),
        ),
    ]
